[package]
name = "cargo-registry"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.2.1"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "Backend of crates.io"

[workspace]

[profile.release]
opt-level = 2

[lib]
name = "cargo_registry"
doctest = false

[[test]]
name = "all"
path = "src/tests/all.rs"

[package.metadata.docs.rs]
rustdoc-args = [
    "--no-defaults",
    "--passes", "collapse-docs",
    "--passes", "unindent-comments"
]

[dependencies]
cargo-registry-s3 = { path = "src/s3", version = "0.2.0" }
rand = "0.3"
git2 = "0.6.4"
flate2 = "0.2"
semver = "0.5"
url = "1.2.1"
tar = "0.4.13"

r2d2 = "0.7.0"
openssl = "0.9.14"
curl = "0.4"
oauth2 = "0.3"
log = "0.3"
env_logger = "0.4"
hex = "0.2"
license-exprs = "^1.3"
dotenv = "0.10.0"
toml = "0.4"
diesel = { version = "0.16.0", features = ["postgres", "serde_json", "chrono"] }
diesel_codegen = "0.16.0"
r2d2-diesel = "0.16.0"
diesel_full_text_search = "0.16.0"
serde_json = "1.0.0"
serde_derive = "1.0.0"
serde = "1.0.0"
clippy = { version = "=0.0.162", optional = true }
chrono = { version = "0.4.0", features = ["serde"] }
comrak = { version = "0.1.9", default-features = false }
ammonia = "0.7.0"
docopt = "0.8.1"
itertools = "0.6.0"
lettre = "0.6"

conduit = "0.8"
conduit-conditional-get = "0.8"
conduit-cookie = "0.8"
cookie = "0.9"
conduit-json-parser = "0.8"
conduit-log-requests = "0.8"
conduit-middleware = "0.8"
conduit-router = "0.8"
conduit-static = "0.8"
conduit-git-http-backend = "0.8"
civet = "0.9"

[dev-dependencies]
conduit-test = "0.8"
hyper = "0.11"
hyper-tls = "0.1"
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"

[build-dependencies]
dotenv = "0.10"
diesel = { version = "0.16.0", features = ["postgres"] }

[features]
unstable = []
lint = ["clippy"]
